### ISSUE TITLE
Undefined method 'join'

### ISSUE THREAD

**Issue by adeleglise** [gooddata/serverspec-core#52]
Hello,
When I run the job, an error is throwed :

```bash
bundle exec rake spec
rake aborted!
NoMethodError: undefined method `join' for nil:NilClass
Did you mean?  JSON
/home/xxxxxxxxx/serverspec-core/Rakefile:122:in `block (4 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rspec-core-3.3.2/lib/rspec/core/rake_task.rb:86:in `block (2 levels) in define'
/var/lib/gems/2.3.0/gems/rspec-core-3.3.2/lib/rspec/core/rake_task.rb:85:in `block in define'
Tasks: TOP => spec => check:server:all => check:server:xxxxxxxxxxxxxxxxxxxxxx
(See full trace by running task with --trace)
```

Am I missing something ?

**Comment by adeleglise** [comment]
Ok found it, missing the suite name in the yaml file.
